// LOAD SOUNDS
const path = `./sounds/`
const sfxBoom = new Audio(path+'Boom.wav');
sfxBoom.volume = 0.75;
const sfxBulletImpact = new Audio('./sounds/BulletImpact.wav');
const sfxEPE = new Audio('./sounds/EnemyPlaneExplosion.wav');
const sfxExtraLife = new Audio('./sounds/ExtraLife.wav');
const sfxGameStart = new Audio(path+'GameStart.wav');
const sfxLevelUp = new Audio(path+'LevelUp.wav');
const sfxMedal = new Audio(path+'Medal.wav');
const sfxMenuMove = new Audio(path+'MenuMove.wav');
const sfxMenuSelect = new Audio(path+'MenuSelect.wav');
const sfxPause = new Audio(path+'Pause.wav');
const sfxPlayerHit = new Audio(path+'PlayerHit.wav');
const sfxPPE = new Audio(path+'PlayerPlaneExplosion.wav');
const sfxPSF = new Audio(path+'PlayerShotF.wav');
const sfxPSM = new Audio(path+'PlayerShotM.wav');
const sfxPSS = new Audio(path+'PlayerShotS.wav');
const sfxPowerUp = new Audio(path+'PowerUp.wav');
const sfxSupply = new Audio(path+'sfx_vehicle_plainloop.wav');
sfxSupply.loop = true;
const sfxWeapon = new Audio(path+'WeaponPickUp.wav');
const sfxSmallHealth = new Audio(path+'SmallHealth.wav');